development:
  adapter: postgresql
  encoding: unicode
  database: k_academy_development
  host: localhost
  username: postgres
  password: postgres
  pool: 5


# test:
#   adapter: postgresql
#   encoding: unicode
#   database: sparestaff_development
#   host: localhost
#   username: postgres
#   password: postgres
#   pool: 5